services:
  web:
    build: .
    container_name: apacheguillermo
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"
    networks:
      - app_network
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: basededatos
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: guillermo
      MYSQL_DATABASE: guillermo
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: xamppphpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
    networks:
      - app_network

networks:
  app_network:

volumes:
  db_data:
